[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'fholgado/minibufexpl.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'dense-analysis/ale'
