[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'fholgado/minibufexpl.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
